### ISSUE TITLE
如果是后端排序@sort-change事件用超多的，期待大佬加上

### ISSUE THREAD

**Issue by Jim-jw** [livelyPeng/pl-table#12]
pl-table可以使用原el-table的@header-click的事件，可以获取排序需要传给后端的值

**Comment by Jim-jw** [comment]
pl-table可以使用原el-table的@header-click的事件，可以获取需要传给后端的值

**Comment by livelyPeng** [comment]
加上了哦

**Comment by Jim-jw** [comment]
> 加上了哦

稳👍
