### ISSUE TITLE
datas 数据类型不合法时 chrome标签卡死

### ISSUE THREAD

**Issue by zl7261** [livelyPeng/pl-table#15]
```html
<pl-table :datas="events" 
                  use-virtual
                  :row-height="45"
                  :paginationShow="false">
</pl-table>
```
```javascript
data(){
return {
events: {}
}}
```

当events声明为对象时,会造成浏览器标签页无响应, favicon一直在转,
卡死的标签cpu占用率维持在25%,消耗300MB内存

是有在轮询什么数据吗?
不应该先去执行typeof datas===array,
然后抛出数据异常错误吗?

**Comment by livelyPeng** [comment]
哈哈哈 这个我还没测试 感谢感谢，不过这样的情况不多吧， 本来就是传数组  结构搞个对象

**Comment by livelyPeng** [comment]
@zl7261 element表格传入对象 一样会卡死  哈哈哈，不对呀 人家明明给你说了传入数组  哈哈

**Comment by zl7261** [comment]
> @zl7261 element表格传入对象 一样会卡死 哈哈哈，不对呀 人家明明给你说了传入数组 哈哈

还是不一样的,element会快速抛出这个类型异常,并不会导致favicon一直在转

**Comment by livelyPeng** [comment]
@??ele我传个对象 一样的啊&nbsp; 为啥&nbsp; &nbsp; 哎小问题&nbsp; 下个版本判断下&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zl7261"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 下午5:43
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-table] datas 数据类型不合法时 chrome标签卡死 (#15)



 
@zl7261 element表格传入对象 一样会卡死 哈哈哈，不对呀 人家明明给你说了传入数组 哈哈
  
还是不一样的,element会快速抛出这个类型异常,并不会导致favicon一直在转

**Comment by livelyPeng** [comment]
最新版本 不存在传入对象 页面卡死啦
