### ISSUE TITLE
为啥源码拉下来按照依赖后启动会报错？

### ISSUE THREAD

**Issue by chaos-zhu** [livelyPeng/pl-table#16]
![image](https://user-images.githubusercontent.com/44160914/69021450-cf20f280-09f2-11ea-9595-c91fe1a150ce.png)

**Comment by livelyPeng** [comment]
第一源码启动不起来的哈，没有dev的       第二github上是部分源码，启动不起来的哈，

**Comment by livelyPeng** [comment]
主要呢在于怎么用，不在于源码，项目是打包后的， 源码就是element源码，然后改了element源码，完了，  也就是说 你看ele源码就完事啦
