### ISSUE TITLE
table slot显示不正常,slot=empty,append

### ISSUE THREAD

**Issue by zl7261** [livelyPeng/pl-table#17]
API文档中有写到 

空数据时显示的文本内容,也可以通过 slot="empty" 设置

https://github.com/livelyPeng/pl-table/wiki/Component-API-2.4.6%E5%8F%8A%E4%BB%A5%E4%B8%8A%E7%89%88%E6%9C%AC

```html
  <template slot="empty">
                <icon class="el-icon-warning-outline"></icon>
                没有查询到符合条件的记录
</template>
```
但其实用slot的方式,没有正常显示

但是pl-table.js 8264行又有对这个empty slot的实现 
_vm._t("empty")

当前版本    "pl-table": "^2.4.7",

**Comment by livelyPeng** [comment]
升级2.4.8

**Comment by livelyPeng** [comment]
<template slot="empty"&gt;                 没有查询到符合条件的记录 </template&gt;
 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zl7261"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 晚上6:06
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-table] 无数据时,slot=&quot;empty不显示&quot; (#17)




Closed #17.

**Comment by zl7261** [comment]
```html
<div slot="append">
哈哈哈
</div>
```
没有被渲染

**Comment by livelyPeng** [comment]
这个还没有加入哦  你用这个干嘛

**Comment by zl7261** [comment]
> 这个还没有加入哦 你用这个干嘛

有个分页需求,
但后台可以提供数据查询接口,不能提供分页接口,,
想用这个 append slot来提示数据是否查询完毕了.
看来得换个办法了

**Comment by livelyPeng** [comment]
那你自己去操作dom啊&nbsp; 多简单的事 小问题啊&nbsp; 自己去布局模仿个啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zl7261"<notifications@github.com&gt;; 
发送时间: 2019年11月19日(星期二) 下午3:09
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-table] table slot显示不正常,slot=empty,append (#17)



 
这个还没有加入哦 你用这个干嘛
  
有个分页需求,
 但后台可以提供数据查询接口,不能提供分页接口,,
 想用这个 append slot来提示数据是否查询完毕了.
 看来得换个办法了

**Comment by zl7261** [comment]
> 那你自己去操作dom啊&nbsp; 多简单的事 小问题啊&nbsp; 自己去布局模仿个啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zl7261"<notifications@github.com&gt;; 发送时间: 2019年11月19日(星期二) 下午3:09 收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [livelyPeng/pl-table] table slot显示不正常,slot=empty,append (#17) 这个还没有加入哦 你用这个干嘛 有个分页需求, 但后台可以提供数据查询接口,不能提供分页接口,, 想用这个 append slot来提示数据是否查询完毕了. 看来得换个办法了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.



> 那你自己去操作dom啊&nbsp; 多简单的事 小问题啊&nbsp; 自己去布局模仿个啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zl7261"<notifications@github.com&gt;; 发送时间: 2019年11月19日(星期二) 下午3:09 收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [livelyPeng/pl-table] table slot显示不正常,slot=empty,append (#17) 这个还没有加入哦 你用这个干嘛 有个分页需求, 但后台可以提供数据查询接口,不能提供分页接口,, 想用这个 append slot来提示数据是否查询完毕了. 看来得换个办法了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

嗯,但你的代码里面,有对这个append slot的操作,尽管没有渲染出来

**Comment by livelyPeng** [comment]
小问题哈，下个版本在加进去，你这个东西基本没人用得着
