### ISSUE TITLE
表格设置row-height为20的时候，有fixed=“right”属性的列高度与没有fixed属性列高度出现差异，导致行无法对齐

### ISSUE THREAD

**Issue by 609067409** [livelyPeng/pl-table#24]
表格设置row-height为20的时候，有fixed=“right”属性的列高度与没有fixed属性列高度出现差异，导致行无法对齐，请大佬看看

**Comment by livelyPeng** [comment]
@609067409 加QQ截图  自己玩法不对

**Comment by 609067409** [comment]
感谢大佬赐教，已解决。

**Comment by wanghuyin** [comment]
> 表格设置row-height为20的时候，有fixed=“right”属性的列高度与没有fixed属性列高度出现差异，导致行无法对齐，请大佬看看
您好,请问这个怎么解决的?
