### ISSUE TITLE
用computed屬性會有資料顯示不完整的問題

### ISSUE THREAD

**Issue by librablue** [livelyPeng/pl-table#43]
用 computed 當 datas 資料來源，computed 裡做了 filter 過濾，有時會出現資料沒全部顯示的問題，
此時只要捲軸動一下又會跑出來了，請問如何解?

**Comment by livelyPeng** [comment]
不知道你可以加群，截图 我看看你咋写的，我自己反正没问题

**Comment by livelyPeng** [comment]
反正也是小问题

**Comment by librablue** [comment]
後來發現只要在computed回傳結果前將捲軸歸0就可以解決了，感謝。
