### ISSUE TITLE
后面多加一列是什么意思？？？

### ISSUE THREAD

**Issue by git-ysz** [livelyPeng/pl-table#5]
![TIM截图20190923171431](https://user-images.githubusercontent.com/31951432/65414202-cd3d1780-de25-11e9-9c3f-cab54b54e72b.png)
![TIM截图20190923171513](https://user-images.githubusercontent.com/31951432/65414203-cd3d1780-de25-11e9-8013-f99a09f341bc.png)

**Comment by git-ysz** [comment]
虽然不明白为什么多加一列，但是解决问题就足够了

**Comment by livelyPeng** [comment]
你可以自己去干掉。或者使用最新版本哦，看文档的掉落元素关键字
