### ISSUE TITLE
pl-tabel设置了use-virtual后 pl-table-column设置fixed='right' 该浮动列的元素会被隐藏 有人遇到过这个问题吗 求指教

### ISSUE THREAD

**Issue by jingjing1117** [livelyPeng/pl-table#55]
```
<pl-table
  ref='table'
  :datas='tableData'
  :height='tableHeight'
  row-key='id'
  use-virtua
>
  .......
       <pl-table-column label="操作" v-if="editState" fixed="right" width="120" align="center">
          <template slot-scope="scope">
            <el-button type="text" @click="edit(scope.row)">编辑</el-button>
          </template>
        </pl-table-column>

</pl-table>
```

操作那列浮动到右边了但是按钮没有显示出来

**Comment by wanghuyin** [comment]
> ```
> <pl-table
>   ref='table'
>   :datas='tableData'
>   :height='tableHeight'
>   row-key='id'
>   use-virtua
> >
>   .......
>        <pl-table-column label="操作" v-if="editState" fixed="right" width="120" align="center">
>           <template slot-scope="scope">
>             <el-button type="text" @click="edit(scope.row)">编辑</el-button>
>           </template>
>         </pl-table-column>
> 
> </pl-table>
> ```
> 
> 操作那列浮动到右边了但是按钮没有显示出来
您好,我也遇到了同样的问题, 请问您解决了吗,如何解决的?

**Comment by jingjing1117** [comment]
> > ```
> > <pl-table
> >   ref='table'
> >   :datas='tableData'
> >   :height='tableHeight'
> >   row-key='id'
> >   use-virtua
> > >
> >   .......
> >        <pl-table-column label="操作" v-if="editState" fixed="right" width="120" align="center">
> >           <template slot-scope="scope">
> >             <el-button type="text" @click="edit(scope.row)">编辑</el-button>
> >           </template>
> >         </pl-table-column>
> > 
> > </pl-table>
> > ```
> > 
> > 
> > 操作那列浮动到右边了但是按钮没有显示出来
> > 您好,我也遇到了同样的问题, 请问您解决了吗,如何解决的?

没有引入样式文件导致的
