### ISSUE TITLE
同一份代码在不同环境编译，最终的html结果不一样，如下图

### ISSUE THREAD

**Issue by BraveWay** [livelyPeng/pl-table#57]
![image](https://user-images.githubusercontent.com/26640031/80579629-f1f11180-8a3c-11ea-8bf9-25d9a195b5cd.png)
![image](https://user-images.githubusercontent.com/26640031/80579679-0503e180-8a3d-11ea-9e98-0e96c7fab060.png)
其中少了一个div，class 为ant-table-scroll  造成页面显示效果不一样

**Comment by livelyPeng** [comment]
版本不一样 仔细检查

**Comment by BraveWay** [comment]
> 版本不一样 仔细检查

node 版本是不一样的 ，是这个原因吗？

**Comment by livelyPeng** [comment]
pl-table版本不一样啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BraveWay"<notifications@github.com&gt;; 
发送时间: 2020年4月29日(星期三) 下午5:55
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-table] 同一份代码在不同环境编译，最终的html结果不一样，如下图 (#57)





  
版本不一样 仔细检查
  
node 版本是不一样的 ，是这个原因吗？

**Comment by BraveWay** [comment]
> pl-table版本不一样啊
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BraveWay"<notifications@github.com&gt;; 发送时间: 2020年4月29日(星期三) 下午5:55 收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [livelyPeng/pl-table] 同一份代码在不同环境编译，最终的html结果不一样，如下图 (#57) 版本不一样 仔细检查 node 版本是不一样的 ，是这个原因吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

服务器和本地是同一份代码，pl-table应该不存在版本的差异吧

**Comment by pengliheng** [comment]
为什么没有 el-table 那种层级渲染.//

**Comment by livelyPeng** [comment]
听不懂

**Comment by pengliheng** [comment]
就是有 children 栏
![image](https://user-images.githubusercontent.com/14355994/87527499-cafebf00-c6be-11ea-80f4-59a2dfef9f58.png)

**Comment by livelyPeng** [comment]
没看懂 加群吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peng, LiHeng"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 下午5:16
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-table] 同一份代码在不同环境编译，最终的html结果不一样，如下图 (#57)





 
就是有 children 栏

**Comment by pengliheng** [comment]
就是树表

**Comment by livelyPeng** [comment]
加群啊&nbsp; 大哥 有树形表格&nbsp; 看文档啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Peng, LiHeng"<notifications@github.com&gt;; 
发送时间: 2020年7月15日(星期三) 下午5:20
收件人: "livelyPeng/pl-table"<pl-table@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-table] 同一份代码在不同环境编译，最终的html结果不一样，如下图 (#57)





 
就是树表
