### ISSUE TITLE
plx-table-column嵌套的时候拖动内容更新有问题

### ISSUE THREAD

**Issue by Hansuku** [livelyPeng/pl-table#68]
`
<plx-table-grid :data="data" ref="plTable" height="500" :highlight-current-row="false" :fit="false" :select-on-indeterminate="false" :row-height="50" :span-method="spanMethod">

      <plx-table-column v-for="(item, index) in head" :key="index" :label="item.attrName" :prop="item.attr" :width="300" :resizable="false" align="center">
        <plx-table-column label="1" prop="1" :width="150" :resizable="false" align="center" />
      </plx-table-column>
</plx-table-grid>
`
主要是为了实现多级表头，这种情况下拖动 X 轴滚动，会发现滚动条可以动但是表头永远是那几个，不会切换

**Comment by a810946378** [comment]
请问怎么解决了呢？为什么关闭了，我现在也遇到了这个问题
