### ISSUE TITLE
reloadData方法 不生效

### ISSUE THREAD

**Issue by zxk175** [livelyPeng/pl-table#74]
@livelyPeng 

![image](https://user-images.githubusercontent.com/10259995/86081281-93412600-bac7-11ea-8643-97155918a342.png)

![image](https://user-images.githubusercontent.com/10259995/86081240-799fde80-bac7-11ea-9594-e95811a8df72.png)

**Comment by livelyPeng** [comment]
tableData没数据吧 加群吧

**Comment by zxk175** [comment]
是因为没数据
