### ISSUE TITLE
什么时候兼容vue3.0

### ISSUE THREAD

**Issue by lifedre** [livelyPeng/pl-table#75]
element支持3.0计划看不到，想摆脱element换ant-design，但是自己小改的table组件基于el-table换不了。

**Comment by livelyPeng** [comment]
听不懂啊  加群 不知道你想干嘛

**Comment by lifedre** [comment]
新项目想上vue3.0

**Comment by livelyPeng** [comment]
是cli3.0  还是vue.30  vue.3都还没出来
