### ISSUE TITLE
设置最小宽属性无效 ，设置宽却可以

### ISSUE THREAD

**Issue by dbl520** [livelyPeng/pl-table#85]
<pl-table-column v-for="item in columns" 
						 :key="item.id" 
						 :show-overflow-tooltip="item.showOverflowTooltip"
						 :prop="item.prop"
						 sortable
						 align='center'
						 :label="item.label+(item.width)" 
						 :fixed="item.fixed" 
						 :min-width="item.width" >

**Comment by livelyPeng** [comment]
你这个问题   我删除了啊，  是可以的哈，你是对最小宽理解有问题
